apiVersion: v1
data:
  .htpasswd: YWRtaW46JGFwcjEkdmdPTXRURFgkMmhOZGVQdjVsWTBoUUNYa1dicG4xMQ==
kind: Secret
metadata:
  name: basic-auth
  namespace: linkerd
type: Opaque
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: linkerd
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:8084;
      proxy_set_header Origin "";
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  #- host: dashboard.example.com
  - http:
      paths:
      - backend:
          serviceName: linkerd-web
          servicePort: 8084
        path: /linkerd(/|$)(.*)