version: '3.4'

services:
  containername:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MessageBus__ConnectionString=amqp://guest:guest@rabbitmq
      - Database__ConnectionString=mongodb://mongodb
      - ServiceConfiguration__ConnectionString=http://consul:8500
    build:
      args:
        RUNTIME_IMAGE_VERSION: aspnetcore-runtime
        SDK_IMAGE_VERSION: sdk
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro