#https://lernentec.com/post/running-simple-elasticsearch-kibana-minikube/
kind: PersistentVolume
apiVersion: v1
metadata:
  name: es-pv-volume
  labels:
    type: local
    k8s-app: elasticsearch
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: \C\kubevolumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-clain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  serviceName: "elasticsearch"
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
        k8s-app: elasticsearch
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: elasticsearch-clain
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
        env:
        - name: discovery.type
          value: single-node
        ports:
        - containerPort: 9200
          name: client
        - containerPort: 9300
          name: nodes
        volumeMounts:
        - name: data
          mountPath: \C\kubevolumes
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    service: elasticsearch
    k8s-app: elasticsearch
spec:
  ports:
  - port: 9200
    name: client
  - port: 9300
    name: nodes
  selector:
    app: elasticsearch