sidecar:
  image: xuxinkun/k8s-sidecar:0.0.7
  imagePullPolicy: IfNotPresent
  datasources:
    enabled: true
    label: grafana_datasource
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: default
      orgId: 1
      folder: 
      type: file
      disableDeletion: true
      editable: false
      options:
        path: /var/lib/grafana
default:
  node-exporter:
    gnetId: 1860
    revision: 14
    datasource: Prometheus