
# https://www.hashicorp.com/blog/hashicorp-consul-1-5
# https://learn.hashicorp.com/consul/developer-mesh/l7-observability-k8s
# git clone https://github.com/hashicorp/consul-helm.git
# helm install -f helm-consul-values.yaml ./consul-helm
# Choose an optional name for the datacenter
global:
  datacenter: dc1
  image: "consul:1.5.3"
  bootstrapACLs: false
# Enable the Consul Web UI via a NodePort
ui:
  service:
    type: 'NodePort'

# Enable Connect for secure communication between nodes
connectInject:
  enabled: true
  certs:
    caBundle: "Wladimir"
  # inject an envoy sidecar into every new pod,
  # except for those with annotations that prevent injection
  default: true
  # these settings enable L7 metrics collection and are new in 1.5
  centralConfig:
    enabled: true
    # set the default protocol (can be overwritten with annotations)
    defaultProtocol: 'http'
    # tell envoy where  to send metrics
    # proxyDefaults: |
    #   {
    #     "envoy_prometheus_bind_addr": "http://prometheus-server.kube-logging.svc.cluster.local"
    #   }
    proxyDefaults: |
      {
      "envoy_dogstatsd_url": "udp://127.0.0.1:9125"
      }
  # namespaceSelector: 'dev'
client:
  enabled: true
  grpc: true
# Use only one Consul server for local development
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0

syncCatalog:
  enabled: true
