apiVersion: v1
kind: Namespace
metadata:
  name: dev
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: homolog
  annotations:
    linkerd.io/inject: enabled